on:
  workflow_call:

name: R-CMD-check-core.yaml

permissions:
  contents: read

jobs:
  R-CMD-check-linux:
    name: Core R-CMD-check â€“ ubuntu-latest (${{ matrix.r }})
    runs-on: ubuntu-latest
    # Run the job inside a Rocker image
    container:
      image: ${{ (matrix.r == 'release' && 'Public-Health-Scotland/actions/phs-r-image') || (matrix.r == 'devel' && 'rocker/r-ver:devel') || format('rocker/r-ver:{0}', matrix.r) }}
            
    strategy:
      fail-fast: false
      matrix:
        # Just add versions here; mapping happens above
        r:
          - release   # current CRAN release
          - '4.4.2'   # Posit Workbench baseline
          - '4.5.1'   # Posit Workbench baseline
          
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - name: Install git and qpdf
        run: |
          apt-get update
          DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends git qpdf
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - uses: r-lib/actions/setup-pandoc@6f6e5bc62fba3a704f74e7ad7ef7676c5c6a2590 # v2.11.4
      - uses: r-lib/actions/setup-r-dependencies@6f6e5bc62fba3a704f74e7ad7ef7676c5c6a2590 # v2.11.4
        with:
          extra-packages: any::rcmdcheck
          needs: check
      - uses: r-lib/actions/check-r-package@6f6e5bc62fba3a704f74e7ad7ef7676c5c6a2590 # v2.11.4
        with:
          upload-snapshots: true
          build_args: 'c("--no-manual","--compact-vignettes=gs+qpdf")'
          
